"""Self-contained HTML player / correction helper written next to the PNG sheet (data/audio/sheet.html).

Open it in a browser (double-click; no server needed). Pick the audio file with the file button if the relative path does not load.
  * timeline: sections, bars, beats, words (green recognised / orange interpolated / blue pinned), non-lyric vocalisations, playhead
  * karaoke line with the current word highlighted, current section / bar / beat
  * click a word or line to seek there; space = play/pause; [ and ] = -2 s / +2 s; the speed selector slows playback to 0.5x
  * hand correction: "set t0 = now" / "set t1 = now" next to every word; tap-along: select a word, play, press N at every word start
    (records the times of the following words); section start / end buttons. Everything lands in the overrides box, which you can
    copy or download as overrides.json (put it in data/, re-run stage 7:  python3 -m zcaudio run ... --stages 7,8).
"""
from __future__ import annotations

import json
import os

TEMPLATE = r"""<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Timing sheet</title>
<style>
:root{--bg:#15121a;--fg:#eee;--dim:#9a94a6;--card:#221d2b;--asr:#2e9b47;--interp:#e08a1e;--pinned:#2f6fd0;--acc:#ff6fa8}
body{margin:0;background:var(--bg);color:var(--fg);font:13px/1.4 system-ui,sans-serif}
header{position:sticky;top:0;z-index:5;background:#0e0c12;padding:8px 12px;border-bottom:1px solid #333;display:flex;gap:12px;align-items:center;flex-wrap:wrap}
header b{color:var(--acc)} audio{height:34px;width:min(520px,100%)}
#now{font-variant-numeric:tabular-nums;color:var(--dim)}
#kar{padding:10px 14px;font-size:22px;min-height:34px}
#kar span{opacity:.45} #kar span.on{opacity:1;color:var(--acc)} #kar span.done{opacity:.9}
a{color:#8fd3ff}
canvas{width:100%;height:230px;display:block;background:#0e0c12;cursor:pointer}
.wrap{padding:0 12px 40px}
table{border-collapse:collapse;width:100%} td,th{padding:2px 6px;border-bottom:1px solid #2b2533;text-align:left;white-space:nowrap}
tr.line td{background:var(--card);font-weight:600} tr.flag td{color:#ffcf6b} tr.cur td{outline:1px solid var(--acc)}
.src-asr{color:var(--asr)} .src-interp{color:var(--interp)} .src-pinned{color:var(--pinned)}
button,select,input[type=file]{background:#2c2537;color:var(--fg);border:1px solid #453b55;border-radius:4px;padding:2px 6px;font-size:12px}
textarea{width:100%;height:150px;background:#0e0c12;color:#cfe;border:1px solid #333;font:12px monospace}
.small{color:var(--dim);font-size:12px} h3{margin:14px 0 4px}
</style></head><body>
<header><b>Timing sheet</b><audio id="au" controls preload="auto"></audio>
<input type="file" id="pick" accept="audio/*"><select id="rate"><option value="1">1x</option><option value="0.75">0.75x</option><option value="0.5">0.5x</option></select>
<span id="now"></span><span class="small" id="sec"></span></header>
<div id="kar"></div>
<canvas id="cv"></canvas>
<div class="wrap">
<h3>Overrides <span class="small">(copy or download; save as data/overrides.json, then re-run stages 7,8)</span></h3>
<textarea id="ov" spellcheck="false"></textarea>
<div><button id="dl">download overrides.json</button> <button id="clr">clear</button>
<span class="small"> tap-along: click a word's "tap" button, play, press <b>N</b> at each word start (Esc stops)</span></div>
<h3>Sections</h3><table id="tsec"></table>
<h3>Words</h3><table id="twd"></table>
<p class="small">generated by zcaudio %%PIPELINE%% - %%SONG%% - %%NOTE%%</p></div>
<script>
const T=%%DATA%%;
const AUDIO_REL=%%AUDIO%%;
const au=document.getElementById('au'), cv=document.getElementById('cv'), ctx2=cv.getContext('2d');
const words=T.words, lines=T.lines, secs=T.sections, beats=T.beats, bars=T.bars, dur=T.meta.duration;
const flagged=new Set((T.quality.review||[]).map(r=>r.line));
let view={t0:0,span:30}, cur=-1, tapAt=-1, ov={words:{},sections:{},lines:{}};
if(AUDIO_REL){au.src=AUDIO_REL}
document.getElementById('pick').onchange=e=>{const f=e.target.files[0];if(f){au.src=URL.createObjectURL(f)}};
document.getElementById('rate').onchange=e=>{au.playbackRate=parseFloat(e.target.value)};
const fmt=t=>t.toFixed(3);
function wkey(w){const l=lines[w.line];return l.id+'/'+(w.i-l.word0+1)}
function setOv(){document.getElementById('ov').value=JSON.stringify(ov,(k,v)=>v,1)}
function pin(i,f,t){const w=words[i];const k=wkey(w);ov.words[k]=Object.assign(ov.words[k]||{},{expect:w.n});ov.words[k][f]=+t.toFixed(3);setOv()}
// tables
const tw=document.getElementById('twd');let h='<tr><th>#<th>word<th>t0<th>t1<th>src<th>conf<th><th></tr>';
lines.forEach(l=>{h+=`<tr class="line ${flagged.has(l.id)?'flag':''}"><td colspan=8><a href="#" onclick="seek(${l.t0-0.3});return false">${l.id}</a> ${l.text} <span class="small">${fmt(l.t0)}-${fmt(l.t1)} conf ${l.conf}</span></td></tr>`;
 for(let i=l.word0;i<l.word1;i++){const w=words[i];h+=`<tr id="w${i}"><td>${i}<td><a href="#" onclick="seek(${w.t0-0.2});return false">${w.w}</a><td>${fmt(w.t0)}<td>${fmt(w.t1)}<td class="src-${w.src}">${w.src}<td>${w.conf}<td><button onclick="pin(${i},'t0',au.currentTime)">t0=now</button> <button onclick="pin(${i},'t1',au.currentTime)">t1=now</button> <button onclick="tapAt=${i}">tap</button></tr>`}});
tw.innerHTML=h;
const ts=document.getElementById('tsec');let hs='<tr><th>id<th>sung<th>start<th>end<th>bar<th></tr>';
secs.forEach(s=>{hs+=`<tr><td>${s.id}<td>${fmt(s.t0)}-${fmt(s.t1)}<td>${fmt(s.start)}<td>${fmt(s.end)}<td>${s.bar0}<td><button onclick="ovs('${s.id}','start')">start=now</button> <button onclick="ovs('${s.id}','end')">end=now</button> <button onclick="seek(${s.start-1})">go</button></tr>`});
ts.innerHTML=hs;
function ovs(id,f){ov.sections[id]=Object.assign(ov.sections[id]||{},{[f]:+au.currentTime.toFixed(3)});setOv()}
function seek(t){au.currentTime=Math.max(0,t);au.play()}
document.getElementById('dl').onclick=()=>{const b=new Blob([document.getElementById('ov').value],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='overrides.json';a.click()};
document.getElementById('clr').onclick=()=>{ov={words:{},sections:{},lines:{}};setOv()};
document.getElementById('ov').oninput=e=>{try{ov=JSON.parse(e.target.value)}catch(_){}};
document.addEventListener('keydown',e=>{if(e.target.tagName==='TEXTAREA')return;
 if(e.code==='Space'){e.preventDefault();au.paused?au.play():au.pause()}
 else if(e.key==='['){au.currentTime-=2} else if(e.key===']'){au.currentTime+=2}
 else if(e.key==='n'||e.key==='N'){if(tapAt>=0&&tapAt<words.length){pin(tapAt,'t0',au.currentTime);tapAt++}}
 else if(e.key==='Escape'){tapAt=-1}});
setOv();
// karaoke + timeline
function lineOf(t){let k=0;for(let i=0;i<lines.length;i++){if(lines[i].t0-0.4<=t)k=i}return k}
function draw(){
 const W=cv.clientWidth,H=cv.clientHeight,dpr=devicePixelRatio||1;if(cv.width!==W*dpr){cv.width=W*dpr;cv.height=H*dpr}
 const c=ctx2;c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,W,H);
 const t=au.currentTime;if(t<view.t0+2||t>view.t0+view.span-4){view.t0=Math.max(0,Math.min(dur-view.span,t-4))}
 const X=s=>(s-view.t0)/view.span*W;
 secs.forEach((s,k)=>{c.fillStyle=['#3a2436','#22303f','#2a3a25','#3d3521','#332a44','#1f3a37'][k%6];c.fillRect(X(s.start),0,X(s.end)-X(s.start),H);c.fillStyle='#ddd';c.font='11px sans-serif';c.fillText(s.name,X(s.start)+3,12)});
 c.strokeStyle='#666';bars.forEach((b,k)=>{if(b>=view.t0&&b<=view.t0+view.span){c.beginPath();c.moveTo(X(b),16);c.lineTo(X(b),H);c.stroke();if(k%4==0){c.fillStyle='#888';c.fillText(k,X(b)+2,H-3)}}});
 c.strokeStyle='#a33';beats.forEach(b=>{if(b>=view.t0&&b<=view.t0+view.span){c.beginPath();c.moveTo(X(b),H-16);c.lineTo(X(b),H-8);c.stroke()}});
 (T.vocalizations||[]).forEach(v=>{c.fillStyle='rgba(180,180,180,.35)';c.fillRect(X(v.t0),H-40,X(v.t1)-X(v.t0),12)});
 words.forEach(w=>{if(w.t1<view.t0||w.t0>view.t0+view.span)return;const y=30+(w.i%4)*36;c.fillStyle={asr:'#2e9b47',interp:'#e08a1e',pinned:'#2f6fd0'}[w.src]||'#777';
  c.globalAlpha=w.conf<0.5?0.45:0.85;c.fillRect(X(w.t0),y,Math.max(2,X(w.t1)-X(w.t0)),26);c.globalAlpha=1;c.fillStyle='#fff';c.font='11px sans-serif';c.fillText(w.w,X(w.t0)+2,y+17)});
 c.strokeStyle='#ff6fa8';c.lineWidth=2;c.beginPath();c.moveTo(X(t),0);c.lineTo(X(t),H);c.stroke();c.lineWidth=1;
 // karaoke
 const li=lineOf(t),l=lines[li];let k='';for(let i=l.word0;i<l.word1;i++){const w=words[i];k+=`<span class="${t>=w.t1?'done':(t>=w.t0?'on':'')}">${w.w} </span>`}
 document.getElementById('kar').innerHTML=k;
 let bi=0;while(bi+1<beats.length&&beats[bi+1]<=t)bi++;let br=0;while(br+1<bars.length&&bars[br+1]<=t)br++;
 const s=secs.filter(s=>t>=s.start&&t<s.end)[0];
 document.getElementById('now').textContent=t.toFixed(2)+' s  bar '+br+' beat '+((bi-(beats.indexOf(bars[br])))%4+1);
 document.getElementById('sec').textContent=s?s.name+(tapAt>=0?'   [tap-along at word '+tapAt+' "'+words[tapAt].w+'"]':''):'';
 requestAnimationFrame(draw)}
cv.onclick=e=>{const r=cv.getBoundingClientRect();seek(view.t0+(e.clientX-r.left)/r.width*view.span)};
cv.onwheel=e=>{e.preventDefault();view.span=Math.max(5,Math.min(90,view.span*(e.deltaY>0?1.15:0.87)))};
requestAnimationFrame(draw);
</script></body></html>
"""


def write_html(ctx, timing: dict, path):
    keep = {k: timing[k] for k in ("meta", "tempo", "beats", "bars", "sections", "lines", "words", "vocalizations")}
    keep["quality"] = {"review": timing["quality"].get("review", [])}
    words = [{k: w[k] for k in ("i", "w", "n", "t0", "t1", "conf", "src", "line") if k in w} for w in timing["words"]]
    keep["words"] = words
    data = json.dumps(keep, separators=(",", ":"), ensure_ascii=False)
    audio = None
    src = ctx.song or None
    if src and os.path.exists(src):
        audio = os.path.relpath(str(src), os.path.dirname(str(path)))
    html = (TEMPLATE.replace("%%DATA%%", data).replace("%%AUDIO%%", json.dumps(audio)).replace("%%PIPELINE%%", str(timing["meta"]["pipeline"]))
            .replace("%%SONG%%", str(timing["meta"]["song"])).replace("%%NOTE%%", "words: green recognised, orange interpolated, blue pinned"))
    with open(path, "w") as f:
        f.write(html)
